cmake_minimum_required(VERSION 4.3)
project(1stSem_CPLab)

set(CMAKE_CXX_STANDARD 26)

add_executable(1stSem_CPLab main.cpp
        "Lab 1/Task1.cpp"
        "Lab 2/Task1.cpp"
        "Lab 2/Task2.cpp"
        Lab3/Task1.cpp
        Lab3/Task2.cpp
        Lab4/Task1.cpp
        Lab4/Task2.cpp
        Lab5/Task1.cpp
        Lab5/Task2.cpp
        Lab6/Task1.cpp
        Lab7/Task1.cpp
        Lab7/Task2.cpp
        Lab9/Task1.cpp
        Lab10/Task1.cpp
        Lab10/Task2.cpp
        Lab11/Task1.cpp
        Lab11/Task2.cpp
        Lab12/Task1.cpp
        Lab12/Task2.cpp
        Lab13/Task1.cpp
        Lab13/Task2.cpp
        Lab13/Task3.cpp
        Lab14/Task1.cpp
        Lab14/Task2.cpp
        Lab14/Task2.cpp
        Lab14/Task2.cpp
        Lab14/Task3.cpp)
