cmake_minimum_required(VERSION 4.3)
project(1stSem_CPLab)

set(CMAKE_CXX_STANDARD 26)

add_executable(1stSem_CPLab main.cpp
        "Lab01/Task1.cpp"
        "Lab02/Task1.cpp"
        "Lab02/Task2.cpp"
        Lab03/Task1.cpp
        Lab03/Task2.cpp
        Lab04/Task1.cpp
        Lab04/Task2.cpp
        Lab05/Task1.cpp
        Lab05/Task2.cpp
        Lab06/Task1.cpp
        Lab07/Task1.cpp
        Lab07/Task2.cpp
        Lab09/Task1.cpp
        Lab10/Task1.cpp
        Lab10/Task2.cpp
        Lab11/Task1.cpp
        Lab11/Task2.cpp
        Lab12/Task1.cpp
        Lab12/Task2.cpp
        Lab13/Task1.cpp
        Lab13/Task2.cpp
        Lab13/Task3.cpp
        Lab14/Task1.cpp
        Lab14/Task2.cpp
        Lab14/Task2.cpp
        Lab14/Task2.cpp
        Lab14/Task3.cpp)
