cmake_minimum_required(VERSION 3.20)
project(1stSem_CPLab)

set(CMAKE_CXX_STANDARD 17)

add_executable(Lab01_Task1 Lab01/Task1.cpp)
add_executable(Lab02_Task1 Lab02/Task1.cpp)
add_executable(Lab02_Task2 Lab02/Task2.cpp)
add_executable(Lab03_Task1 Lab03/Task1.cpp)
add_executable(Lab03_Task2 Lab03/Task2.cpp)
add_executable(Lab04_Task1 Lab04/Task1.cpp)
add_executable(Lab04_Task2 Lab04/Task2.cpp)
add_executable(Lab05_Task1 Lab05/Task1.cpp)
add_executable(Lab05_Task2 Lab05/Task2.cpp)
add_executable(Lab06_Task1 Lab06/Task1.cpp)
add_executable(Lab07_Task1 Lab07/Task1.cpp)
add_executable(Lab07_Task2 Lab07/Task2.cpp)
add_executable(Lab09_Task1 Lab09/Task1.cpp)
add_executable(Lab10_Task1 Lab10/Task1.cpp)
add_executable(Lab10_Task2 Lab10/Task2.cpp)
add_executable(Lab11_Task1 Lab11/Task1.cpp)
add_executable(Lab11_Task2 Lab11/Task2.cpp)
add_executable(Lab12_Task1 Lab12/Task1.cpp)
add_executable(Lab12_Task2 Lab12/Task2.cpp)
add_executable(Lab13_Task1 Lab13/Task1.cpp)
add_executable(Lab13_Task2 Lab13/Task2.cpp)
add_executable(Lab13_Task3 Lab13/Task3.cpp)
add_executable(Lab14_Task1 Lab14/Task1.cpp)
add_executable(Lab14_Task2 Lab14/Task2.cpp)
add_executable(Lab14_Task3 Lab14/Task3.cpp)